language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install coverage codecov pylint
  - pip install .

script:
  - cd tests
  - coverage run $(which nosetests)
  - cd ..
  - pylint clusterstack --rcfile=.pylint.rc

after_success:
  - coverage xml
  - codecov

deploy:
  provider: pypi
  user: msimet
  password:
    secure: secure_token
  on:
    tags: true
    branch: master
    
notifications:
  email:
    on_success: never
    on_failure: change 
